# Generated by Django 3.2 on 2023-03-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230320_2036'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unigue_together',
        ),
    ]
