# Generated by Django 3.2.16 on 2023-03-16 09:06

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[reviews.models.validate_year], verbose_name='Год'),
        ),
    ]
